name: customer_lab # REQUIRED project name (must be lowercase, no spaces)
version: 1.0.0 # semantic version of your project
config-version: 2 # dbt config schema version

profile: customer_lab # must match the profile/environment name in dbt Cloud

model-paths: ["models"] # where dbt looks for models
analysis-paths: ["analysis"]
test-paths: ["tests"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target" # compiled SQL
clean-targets: ["target", "dbt_packages"]

models:
  customer_lab:
    +materialized: view # default materialization
